# Miry
spring:
  application:
    name: PIZZA-SERVICE
  config:
    import: optional:configserver:http://localhost:8888/config
  profiles:
    active: prod
  zipkin:
    base-url: http://localhost:9411
  main:
    allow-circular-references: true