spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
     server:
      git:
        uri: file://C:/Progetti/BestIngage/BestIngage/Intellij/Esercizio2/Esercizio2Micro/Esercizio5/ConfigRepo
        clone-on-start: true

server:
  port: 8888
  servlet:
    context-path: /config
